### ISSUE TITLE
Server crash.

### ISSUE THREAD

**Issue by PsychooYT** [LevelTranic/Vine#1]
:41:46] [Craft Scheduler Thread - 10 - LiteBans/INFO]: [LiteBans] Updates can be downloaded from here:
[15:41:46] [Craft Scheduler Thread - 10 - LiteBans/INFO]: [LiteBans] https://www.spigotmc.org/resources/litebans.3715/
[15:41:47] [Async Chat Thread - #1/INFO]: Flaapu » I need help!!!!!
[15:41:48] [Async Chat Thread - #0/INFO]: MacDaMarco » you showed em yesterday you dont put no gaps
[15:41:48] [ShreddedPaperTickThread-10/INFO]: EXPBOTTLES issued server command: /r do you got diiamonds
[15:41:48] [Async Chat Thread - #0/INFO]: z9k » Flaapu 1v1 im eu
[15:41:49] [ShreddedPaperTickThread-23/INFO]: CommanderJunko lost connection: Disconnected
[15:41:49] [ShreddedPaperTickThread-23/INFO]: [-] CommanderJunko
[15:41:51] [ShreddedPaperTickThread-27/INFO]: EXPBOTTLES issued server command: /r so I can make gear
[15:41:51] [ShreddedPaperTickThread-9/INFO]: COLLINSPEED0609 issued server command: /r food
[15:41:51] [ShreddedPaperTickThread-15/INFO]: agent69xd issued server command: /r nah
[15:41:51] [ShreddedPaperTickThread-13/ERROR]: ShreddedPaperTickThread-13 tried to run a task from the wrong thread: Cannot move entity off-main
[15:41:51] [ShreddedPaperTickThread-13/ERROR]: Extra data: world=world, chunkpos=[11,-2]
[15:41:51] [ShreddedPaperTickThread-13/ERROR]: Server Version: 1.20.6-DEV-03e739a (MC: 1.20.6)
[15:41:51] [ShreddedPaperTickThread-13/ERROR]: Region locks currently held (regionSize=8 chunks): [world=[[-23,12], [-25,11], [-25,13], [-24,11], [-23,11], [-24,12], [-25,12], [-23,13], [-24,13]]]
[15:41:51] [ShreddedPaperTickThread-13/ERROR]: Stack trace:
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:57) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:109) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.papermc.paper.chunk.system.entity.EntityLookup.moveEntity(EntityLookup.java:513) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.onMove(EntityLookup.java:876) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:4853) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:4814) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.Entity.moveTo(Entity.java:2163) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.internalTeleport(ServerGamePacketListenerImpl.java:1841) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1798) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.projectile.ThrownEnderpearl.onHit(ThrownEnderpearl.java:87) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:252) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:235) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:69) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.projectile.ThrownEnderpearl.tick(ThrownEnderpearl.java:111) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1490) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1365) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperEntityTicker.tickEntity(ShreddedPaperEntityTicker.java:33) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:77) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:97) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$createTask$5(ShreddedPaperRegionScheduler.java:114) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[15:41:51] [ShreddedPaperTickThread-26/ERROR]: ShreddedPaperTickThread-26 tried to run a task from the wrong thread: May not tick entity scheduler asynchronously
[15:41:51] [ShreddedPaperTickThread-26/ERROR]: Extra data: entity=ServerPlayer['Lupzzzzzzzzzzzzz'/5054, uuid='3b2817fc-0a2b-44e7-a699-65ec33f67f69', l='ServerLevel[world]', x=-3031.60, y=66.70, z=1638.41, cpos=[-190, 102], tl=9542492, v=true](Lupzzzzzzzzzzzzz at -3031.601109831555,66.70408185508236,1638.4091865845462)
[15:41:51] [ShreddedPaperTickThread-26/ERROR]: Server Version: 1.20.6-DEV-03e739a (MC: 1.20.6)
[15:41:51] [ShreddedPaperTickThread-13/ERROR]: Entity threw exception at world:-3031.601109831555,66.70408185508236,1638.4091865845462
java.lang.IllegalStateException: Cannot move entity off-main
	at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:58) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:109) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.papermc.paper.chunk.system.entity.EntityLookup.moveEntity(EntityLookup.java:513) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.onMove(EntityLookup.java:876) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:4853) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.Entity.setPosRaw(Entity.java:4814) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.Entity.moveTo(Entity.java:2163) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.internalTeleport(ServerGamePacketListenerImpl.java:1841) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.teleport(ServerGamePacketListenerImpl.java:1798) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.projectile.ThrownEnderpearl.onHit(ThrownEnderpearl.java:87) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.projectile.Projectile.hitTargetOrDeflectSelf(Projectile.java:252) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:235) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:69) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.entity.projectile.ThrownEnderpearl.tick(ThrownEnderpearl.java:111) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1490) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1365) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperEntityTicker.tickEntity(ShreddedPaperEntityTicker.java:33) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:77) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:97) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$createTask$5(ShreddedPaperRegionScheduler.java:114) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[15:41:51] [ShreddedPaperTickThread-26/ERROR]: Region locks currently held (regionSize=8 chunks): [world=[[2,0], [1,-2], [1,0], [1,-1], [2,-1], [2,-2], [0,-1], [0,0], [0,-2]]]
[15:41:51] [ShreddedPaperTickThread-26/ERROR]: Stack trace:
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:57) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:115) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:146) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$_tickRegion$3(ShreddedPaperChunkTicker.java:80) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:77) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:77) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$createTask$5(ShreddedPaperRegionScheduler.java:114) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[15:41:51] [ShreddedPaperTickThread-26/ERROR]: [ShreddedPaperChunkTicker] Exception ticking region RegionPos[1, -1]
java.lang.IllegalStateException: May not tick entity scheduler asynchronously
	at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:58) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:115) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:146) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$_tickRegion$3(ShreddedPaperChunkTicker.java:80) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:77) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:77) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$createTask$5(ShreddedPaperRegionScheduler.java:114) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[15:41:51] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Ticking thread crash while ticking region RegionPos[1, -1]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$2(ShreddedPaperChunkTicker.java:51) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194) ~[?:?]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:130) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$createTask$5(ShreddedPaperRegionScheduler.java:114) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.IllegalStateException: May not tick entity scheduler asynchronously
	at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:58) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:115) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:146) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$_tickRegion$3(ShreddedPaperChunkTicker.java:80) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:77) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:77) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[vine-1.20.6.jar:1.20.6-DEV-03e739a]
	... 7 more

**Comment by PsychooYT** [comment]
Do you have discord by chance, so i could contact you and give you further information? Mine is: excstwsy

**Comment by 404Setup** [comment]
Does this problem also exist on ShreddedPaper?

**Comment by PsychooYT** [comment]
I don't think so, if you could add me on discord i could give you further information about shreddedpaper.

**Comment by 404Setup** [comment]
OK, I'm opencl, I've sent
