### ISSUE TITLE
Teleporting to a destination.

### ISSUE THREAD

**Issue by PsychooYT** [LevelTranic/Vine#3]
### Stack trace

[12:05:37 INFO]: excstwsy issued server command: /farmlimiter teleport world 176335 68 492027
[12:05:37 ERROR]: ShreddedPaperTickThread-11 tried to run a task from the wrong thread: Can't move entity to async destination
[12:05:37 ERROR]: Extra data: world=world, x=176335 y=? z=492027
[12:05:37 ERROR]: Server Version: 1.20.6-DEV-bc6f8e3 (MC: 1.20.6)
[12:05:37 ERROR]: Region locks currently held (regionSize=8 chunks): [world=[[-1063,-2899], [-1064,-2898], [-1063,-2900], [-1064,-2899], [-1062,-2900], [-1062,-2898], [-1062,-2899], [-1064,-2900], [-1063,-2898]]]
[12:05:37 ERROR]: Stack trace:
java.lang.Throwable: null
        at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:57) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:127) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.world.entity.Entity.moveTo(Entity.java:2155) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.internalTeleport(ServerGamePacketListenerImpl.java:1841) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1496) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1355) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at FarmLimiter (1).jar/me.filoghost.farmlimiter.command.FarmLimiterCommand.teleport(FarmLimiterCommand.java:238) ~[FarmLimiter (1).jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at FarmLimiter (1).jar/me.filoghost.farmlimiter.fcommons.command.sub.annotated.AnnotatedMethodSubCommand.execute(AnnotatedMethodSubCommand.java:63) ~[FarmLimiter (1).jar:?]
        at FarmLimiter (1).jar/me.filoghost.farmlimiter.fcommons.command.sub.SubCommandManager.execute(SubCommandManager.java:62) ~[FarmLimiter (1).jar:?]
        at FarmLimiter (1).jar/me.filoghost.farmlimiter.fcommons.command.ConfigurableRootCommand$BukkitCommandExecutorAdapter.onCommand(ConfigurableRootCommand.java:65) ~[FarmLimiter (1).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[vine-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.lambda$run$0(BukkitCommandNode.java:95) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.SynchronousPluginExecution.execute(SynchronousPluginExecution.java:73) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.SynchronousPluginExecution.executeNoException(SynchronousPluginExecution.java:40) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:97) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:456) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.Commands.performCommand(Commands.java:363) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2286) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2260) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tryHandleChat(ServerGamePacketListenerImpl.java:2426) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChatCommand(ServerGamePacketListenerImpl.java:2254) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.handle(ServerboundChatCommandPacket.java:28) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.handle(ServerboundChatCommandPacket.java:14) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:58) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.ShreddedPaper.lambda$runSync$0(ShreddedPaper.java:21) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:177) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$_tickRegion$3(ShreddedPaperChunkTicker.java:80) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:77) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:77) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$7(ShreddedPaperRegionScheduler.java:127) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[12:05:37 ERROR]: Internal error while executing /farmlimiter
java.lang.RuntimeException: java.lang.IllegalStateException: Can't move entity to async destination
        at FarmLimiter (1).jar/me.filoghost.farmlimiter.fcommons.command.sub.annotated.AnnotatedMethodSubCommand.execute(AnnotatedMethodSubCommand.java:68) ~[FarmLimiter (1).jar:?]
        at FarmLimiter (1).jar/me.filoghost.farmlimiter.fcommons.command.sub.SubCommandManager.execute(SubCommandManager.java:62) ~[FarmLimiter (1).jar:?]
        at FarmLimiter (1).jar/me.filoghost.farmlimiter.fcommons.command.ConfigurableRootCommand$BukkitCommandExecutorAdapter.onCommand(ConfigurableRootCommand.java:65) ~[FarmLimiter (1).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[vine-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.lambda$run$0(BukkitCommandNode.java:95) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.SynchronousPluginExecution.execute(SynchronousPluginExecution.java:73) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.SynchronousPluginExecution.executeNoException(SynchronousPluginExecution.java:40) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:97) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:5) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:456) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.Commands.performCommand(Commands.java:363) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.Commands.performCommand(Commands.java:350) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2286) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2260) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tryHandleChat(ServerGamePacketListenerImpl.java:2426) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChatCommand(ServerGamePacketListenerImpl.java:2254) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.handle(ServerboundChatCommandPacket.java:28) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.handle(ServerboundChatCommandPacket.java:14) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:58) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.ShreddedPaper.lambda$runSync$0(ShreddedPaper.java:21) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:177) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$_tickRegion$3(ShreddedPaperChunkTicker.java:80) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.region.LevelChunkRegion.forEachTickingEntity(LevelChunkRegion.java:77) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker._tickRegion(ShreddedPaperChunkTicker.java:77) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperChunkTicker.lambda$tickRegion$1(ShreddedPaperChunkTicker.java:49) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$6(ShreddedPaperRegionScheduler.java:123) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.lambda$tryLockNow$3(ShreddedPaperRegionLocker.java:111) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryReadOnlyLockNow(ShreddedPaperRegionLocker.java:156) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionLocker.tryLockNow(ShreddedPaperRegionLocker.java:105) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.run(ShreddedPaperRegionScheduler.java:122) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.multipaper.shreddedpaper.threading.ShreddedPaperRegionScheduler.lambda$run$7(ShreddedPaperRegionScheduler.java:127) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalStateException: Can't move entity to async destination
        at io.papermc.paper.util.TickThread.failedTickThreadCheck(TickThread.java:58) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:127) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.world.entity.Entity.moveTo(Entity.java:2155) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.internalTeleport(ServerGamePacketListenerImpl.java:1841) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1496) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1355) ~[vine-1.20.6.jar:1.20.6-DEV-bc6f8e3]
        at FarmLimiter (1).jar/me.filoghost.farmlimiter.command.FarmLimiterCommand.teleport(FarmLimiterCommand.java:238) ~[FarmLimiter (1).jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at FarmLimiter (1).jar/me.filoghost.farmlimiter.fcommons.command.sub.annotated.AnnotatedMethodSubCommand.execute(AnnotatedMethodSubCommand.java:63) ~[FarmLimiter (1).jar:?]
        ... 42 more

### Plugin and Datapack List

.

### Configuration files

.

### Actions to reproduce (if known)

This is caused by either ShreddedPaper or Vine.

### Vine version

Current Vine Server Version: 1.20.6-DEV-bc6f8e3 (MC: 1.20.6)*
* You are running the latest version
Previous: 1.20.6-DEV-f9292d2 (MC: 1.20.6)

**Comment by 404Setup** [comment]
The plugin doesn't seem to support folia and uses a non-teleportAsync, which may be causing the problem.

**Comment by 404Setup** [comment]
I analyzed its code and it indeed used teleport instead of teleportAsync, that's why the error appeared.
